version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - retailpharmacy-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - retailpharmacy-network

networks:
  retailpharmacy-network:
    driver: bridge
